### ISSUE TITLE
Switch claim reconcilers from HasDirectClassReferenceKind to IsManagedKind predicate

### ISSUE THREAD

**Issue by negz** [crossplaneio/stack-aws#17] opened 2019-09-19 00:36 UTC
### What happened?
HasDirectClassReferenceKind does not support static provisioning. crossplane-runtime has been updated with a fix, but this stack must be updated. See crossplaneio/crossplane-runtime#28 for details.

**Comment by negz** [comment] 2019-09-19 00:37
https://github.com/crossplaneio/crossplane-runtime/issues/33

**Comment by hasheddan** [comment] 2019-09-27 16:54
Closing this in favor of #16 and opening an issue of its kind on `stack-gcp`, which is where I believe this was intended to be opened.

**Closed by hasheddan** 2019-09-27 16:54 UTC
Labels: bug
